#!\bin\bash
veras tu al coña
#Joder mamasita
#Joder
for i in {1..10} do
	echo $i #Imprimimos el número por pantalla
	#pilla esto bobi
done
#Mas te vale funcionar
#Comentario 1
#Comentario 2
#Comentario 4
#Comentario 5


#!\bin\bash
veras tu
#Joder
A ver si pillas esto bobi #Joder
for i in {1..10} do
	#Imprimimos el número por pantalla
	echo $i #pilla esto bobi
done
#Mas te vale funcionar
#Comentario 1

#Comentario 2
#Comentario 4
#Comentario 5

#Most used 1
#!\bin\bash
veras tu
#SP-10-Joder
A ver si pillas esto bobi #SP-20-Joder
for i in {1..10} do
	#SP-30-Imprimimos el número por pantalla
	echo $i #SP-40-pilla esto bobi
done
#SP-50-Mas te vale funcionar
#SP-60-Comentario 1 jajjaja
#A ver que hacer
#SP-70-Comentario 2 khe?
#SP-80-Comentario 4 pero
#SP-90-Comentario Josep Pedrerol
#SP-91-Comentario

#Most used 2
#SP-10-Joder
#SP-20-Joder
#SP-30-Imprimimos el número por pantalla
#SP-40-pilla esto bobi
#SP-50-Mas te vale funcionar
#SP-60-Comentario 1 jajjaja
#SP-70-Comentario 2 khe?
#SP-80-Comentario 4 pero
#SP-90-Comentario Josep Pedrerol
#A ver que hacer
#SP-91-Comentario

#Most used 3
#EN-10-Hello
#EN-20-
#EN-30-In
#EN-40-
#EN-50-English
#EN-60-
#EN-70-
#EN-80-
#EN-90-


#!\bin\bash
veras tu
#SP-10-Joder
A ver si pillas esto bobi #SP-20-Joder
for i in {1..10} do
	#SP-30-Imprimimos el número por pantalla
	echo $i #SP-40-pilla esto bobi
done
#SP-50-Mas te vale funcionar
#SP-60-Comentario 1
#A ver que hacer
#SP-70-Comentario 2
#SP-80-Comentario 4
#SP-90-Comentario 5
#SP-91-Vamosss

#!\bin\bash
veras tu
#SP-10-Joder
A ver si pillas esto bobi #SP-20-Joder
for i in {1..10} do
	#SP-30-Imprimimos el número por pantalla
	echo $i #SP-40-pilla esto bobi
done
#SP-41- Hola mundo
#funciona wey
#SP-42- Hombre vamos
#SP-50-Mas te vale funcionar
#SP-60-Comentario 1 jajjaja
#SP-70-A ver que hacer
#SP-80-Comentario 2 khe?
#SP-90-Comentario 4 pero
#SP-100-Comentario Josep Pedrerol
#SP-110-Comentario

